[project]
name = "herogold"
version = "4.0.0"
description = "A single package containing personal utilities."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]
authors = [{ name = "HEROgold" }]
license = { text = "MIT" }

[project.optional-dependencies]
updater = [
    "httpxyz[http2]>=0.42.1"
]
orm = [
    "confkit>=2.1.0",
    "sqlmodel>=0.0.42",
]
api = [
    "fastapi>=0.141.1",
]
services = [
    "watchdog>=6.0.0",
]
all = [
    "herogold[orm,api,services,updater]",
]

[project.urls]
Homepage = "https://github.com/HEROgold/HeroPy"
Repository = "https://github.com/HEROgold/HeroPy.git"
Documentation = "https://github.com/HEROgold/HeroPy#readme"
Issues = "https://github.com/HEROgold/HeroPy/issues"

[build-system]
requires = ["hatchling>=1"]
build-backend = "hatchling.build"

[dependency-groups]
test = [
    "herogold[all]",
    "hypothesis>=6.168.0",
    "psycopg2-binary>=2.9.13",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.ty.src]
exclude = ["tests"]
