
from typing import Protocol, runtime_checkable


@runtime_checkable
class SupportsGT(Protocol):
    def __gt__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsLT(Protocol):
    def __lt__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsGE(Protocol):
    def __ge__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsLE(Protocol):
    def __le__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsEq(Protocol):  # noqa: PLW1641
    def __eq__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsNe(Protocol):
    def __ne__(self, other: object, /) -> bool: ...

@runtime_checkable
class SupportsComparison(Protocol):  # noqa: PLW1641
    """A protocol for rich comparison methods."""

    def __gt__(self, other: object, /) -> bool: ...
    def __lt__(self, other: object, /) -> bool: ...
    def __ge__(self, other: object, /) -> bool: ...
    def __le__(self, other: object, /) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
